services:
  user-database:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5001:5432"
    volumes:
      - user_data:/var/lib/postgresql/data

  auth-service:
    build: .
    ports:
      - "4001:4001"
    env_file:
      - .env
    depends_on:
      - user-database

volumes:
  user_data: